---
- name: Deploy Calculator App with Docker
  hosts: webserver
  become: false

  tasks:

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: vinayksm86/scientific-calculator:latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: scientific-calculator
        image: vinayksm86/scientific-calculator:latest
        state: started
        restart_policy: always
        tty: true
        interactive: true
