---
- name: Deploy Calculator App with Docker
  hosts: webserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python docker SDK (required by Ansible docker modules)
      apt:
        name: python3-docker
        state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: vinayksm86/scientific-calculator:latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: scientific-calculator
        image: vinayksm86/scientific-calculator:latest
        state: started
        restart_policy: always
        tty: true
        interactive: true
